"""Central balance values for the v6 completion loop."""

PURE_HOPE_PRICE = 1_000_000
APPRAISAL_TURNS = 30
GEM_CRAFT_TURNS = 20
COOKING_QUALITY_WEIGHTS = {"보통": 75, "훌륭함": 22, "걸작": 3}
COOKING_QUALITY_MULTIPLIER = {"보통": 1.0, "훌륭함": 1.25, "걸작": 1.6}
DAILY_DELIVERY_TARGET = 6
RECIPE_RESEARCH_PITY = 4
RECIPE_RESEARCH_MONEY = 25_000
RECIPE_RESEARCH_MATERIALS = 2
KOREA_TIMEZONE = "Asia/Seoul"
